In [1]:
import graphlab

In [2]:
sales = graphlab.SFrame('kc_house_data.gl/')

This non-commercial license of GraphLab Create for academic use is assigned to ahmedmagdyno@gmail.com and will expire on February 12, 2018.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\ahmed\AppData\Local\Temp\graphlab_server_1488538795.log.0


In [3]:
import numpy as np

In [38]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1
    features=['constant']+features
    features_sframe=data_sframe[features]
    features_matrix = features_sframe.to_numpy()
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’
    output_sarray=data_sframe[output]
    # this will convert the SArray into a numpy array:
    output_array = output_sarray.to_numpy() # GraphLab Create>= 1.7!!
    return(features_matrix, output_array)

In [82]:
def predict_outcome(feature_matrix, weights):
    feature_matrix=feature_matrix.transpose()
    predictions=np.dot(weights,feature_matrix)
    return(predictions)

In [19]:
def feature_derivative(errors, feature):
    derivative=2*np.dot(errors,feature)
    return(derivative)

In [167]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
    gradient_sum_squares = 0 # initialize the gradient

    while not converged:
        # compute the predictions based on feature_matrix and weights:
        predictions=np.dot(weights,feature_matrix.transpose())
        # compute the errors as predictions - output:
        errors=predictions-output
        # while not converged, update each weight individually:
        derivative=-2*np.dot(errors,feature_matrix)
            # add the squared derivative to the gradient magnitude
        gradient_sum_squares=np.dot(derivative.transpose(),derivative)
        gradient_magnitude = np.sqrt(gradient_sum_squares)
            # update the weight based on step size and derivative:
        weights=weights+(step_size*derivative)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)


In [168]:
train_data,test_data = sales.random_split(.8,seed=0)

In [169]:
simple_features = ['sqft_living']
my_output= 'price'
(simple_feature_matrix, output) = get_numpy_data(train_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [170]:
simple_weights = regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size,tolerance)

In [171]:
simple_weights

array([-46999.88716555,    281.91211912])

In [175]:
test_data[0]

{'bathrooms': 1.0,
 'bedrooms': 3.0,
 'condition': 4L,
 'date': datetime.datetime(2014, 5, 28, 0, 0, tzinfo=GMT +0.0),
 'floors': '1.5',
 'grade': 7L,
 'id': '0114101516',
 'lat': 47.75584254,
 'long': -122.22874498,
 'price': 310000.0,
 'sqft_above': 1430L,
 'sqft_basement': 0L,
 'sqft_living': 1430.0,
 'sqft_living15': 1780.0,
 'sqft_lot': 19901L,
 'sqft_lot15': 12697.0,
 'view': 0L,
 'waterfront': 0L,
 'yr_built': 1927L,
 'yr_renovated': 0L,
 'zipcode': '98028'}

In [177]:
simple_features = ['sqft_living']
my_output= 'price'

In [179]:
(simple_feature_matrix, output) = get_numpy_data(test_data, simple_features, my_output)

In [180]:
p=predict_outcome(simple_feature_matrix,simple_weights)

In [182]:
p[0]

356134.44317092968

In [185]:
err=p-output

In [188]:
RSS1=np.dot(err.transpose(),err)

In [189]:
RSS1

275400047593155.91

In [195]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix, output) = get_numpy_data(train_data, model_features,my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [196]:
simple_weights2= regression_gradient_descent(feature_matrix, output,initial_weights, step_size,tolerance)

In [210]:
(simple_test_matrix, output2) = get_numpy_data(test_data, model_features, my_output)

In [211]:
p1=predict_outcome(feature_matrix,simple_weights2)

In [212]:
p1[0]

276660.26922685339

In [213]:
test_data[0]['price']

310000.0

In [215]:
simple_weights2

array([ -9.99999688e+04,   2.45072603e+02,   6.52795277e+01])

In [216]:
model_features = ['sqft_living', 'sqft_living15']
my_output = 'price'
(feature_matrix1, output1) = get_numpy_data(train_data, model_features,my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [217]:
simple_weights2= regression_gradient_descent(feature_matrix1, output1,initial_weights,step_size,tolerance)

In [218]:
simple_weights2

array([ -9.99999688e+04,   2.45072603e+02,   6.52795277e+01])

In [219]:
(matrix, output2) = get_numpy_data(test_data, model_features, my_output)

In [220]:
p2=predict_outcome(matrix,simple_weights2)

In [221]:
p2[0]

366651.41203655908

In [3]:
import numpy as np
initial_weights = np.array([-47000., 1.])

weights = np.array(initial_weights)

In [4]:
weights

array([ -4.70000000e+04,   1.00000000e+00])